accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.signin, name='login'),
    url(r'^signout/', views.signout, name='signout'),
]

djangoreddit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import posts.views as views_post

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views_post.index, name='home'),
]

posts/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'posts'

urlpatterns = [
  url(r'^create/', views.create, name='create'),
  url(r'^show/(?P<post_id>[0-9]+)/$', views.show, name='show'),
  url(r'^(?P<post_id>[0-9]+)/upvote', views.upvote, name='upvote'),
  url(r'^(?P<post_id>[0-9]+)/downvote', views.downvote, name='downvote'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    url = models.TextField(max_length=255)
    pub_date = models.DateTimeField()
    votes_total = models.IntegerField(default=0)
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title

accounts/views.py
from typing import Dict
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['password_confirmation']:
            try:
                user = User.objects.get(username=request.POST['username'])
                # user = User.objects.get(email=request.POST['email'])
                return render(
                    request,
                    'accounts/signup.html',
                    create_response(False, 'Username already taken.')
                )
            except User.DoesNotExist:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    email=request.POST['email'],
                    password=request.POST['password']
                )
                login(request, user)
                return render(request, 'accounts/signup.html', {
                    'ok': True,
                    'message': 'Welcome to the website!'
                })
        else:
            return render(
                request,
                'accounts/signup.html',
                create_response(False, 'Passwords do not match.')
            )
    else:
        return render(request, 'accounts/signup.html')

def signin(request):
    """Controls the sign in logic for a typical user"""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if username != '' and password != '':
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if 'next' in request.POST:
                    response = redirect(request.POST['next'])
                else:
                    response = render(
                        request,
                        'accounts/signin.html',
                        create_response(True, 'Welcome back!')
                    )
            else:
                response = render(
                    request,
                    'accounts/signin.html',
                    create_response(False, 'You do not have an account.')
                )
        else:
            response = render(
                request,
                'accounts/signin.html',
                create_response(False, 'Information is invalid or missing.')
            )
        return response
    else:
        return render(request, 'accounts/signin.html', {'ok': True})

def signout(request):
    """Controls the sign out logic for a typical user"""
    logout(request)
    return render(
        request,
        'accounts/signin.html',
        create_response(True, 'Signed out')
    )

def create_response(status_ok, message) -> Dict:
    """Generate a typical python dictionary response"""
    return {'ok': status_ok, 'message': message}

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from . import models

# Create your views here.

def index(request):
    posts = models.Post.objects.order_by('-pub_date')
    return render(request, 'posts/index.html', {
        'posts': posts
    })

@login_required
def create(request):
    if request.method == 'POST':
        title = request.POST['title']
        url = request.POST['url']
        if title and url and validate_url(url):
            post = models.Post()
            post.title = title
            post.url = url
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect("/posts/show/{}".format(post.id))
        else:
            return render(request, 'posts/create.html', {
              'ok': False,
              'message': 'Invalid or missing information.'
            })
    else:
        return render(request, 'posts/create.html', {
            'ok': True,
            'message': ''
        })

def show(request, post_id):
    post = get_object_or_404(models.Post, pk=post_id)
    return render(request, 'posts/show.html', {'post': post})

def upvote(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(models.Post, pk=post_id)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(models.Post, pk=post_id)
        post.votes_total -= 1
        post.save()
        return redirect('home')

def validate_url(url: str) -> bool:
    return url.startswith('http://') or url.startswith('https://')

accounts/templates/accounts/signin.html
{% if ok %}
<p style="color: green;">{{ message }}</p>
{% else %}
<p style="color: red;">{{ message }}</p>
{% endif %}
<h1>sign in</h1>

<form method="POST" action="{% url 'accounts:login' %}">
  {% csrf_token %}

  {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}" />
  {% endif %}

  <label>Username</label>
  <br/>
  <input type="text" name="username" value="" />
  <br/>
  <label>Password</label>
  <br/>
  <input type="password" name="password" value="" />
  <br/>
  <input type="submit" value="Sign In" />
</form>

accounts/templates/accounts/signup.html
{% if ok %}
<p style="color: green;">{{ message }}</p>
{% else %}
<p style="color: red;">{{ message }}</p>
{% endif %}

<h1>Sign up page</h1>

<form method="POST" action="{% url 'accounts:signup' %}">
  {% csrf_token %}
  <label>Username</label>
  <input type="text" name="username" />
  <br/>
  <label>Email</label>
  <input type="text" name="email" />
  <br/>
  <label>Password</label>
  <input type="password" name="password" />
  <br/>
  <label>Password Confirmation</label>
  <input type="password" name="password_confirmation" />
  <br/>
  <input type="submit" value="Sign up now!" />
</form>

posts/templates/posts/create.html
<h1>Create a new post</h1>

{% if ok %}
{% else %}
<p style="color: red;">{{ message }}</p>
{% endif %}

<form method="POST" action="{% url 'posts:create' %}">
  {% csrf_token %}
  <label>Post Title</label>
  <br/>
  <input type="text" name="title" />
  <br/>
  <label>Post URL</label>
  <br/>
  <input type="text" name="url" />
  <br/>
  <input type="submit" value="Create New Post" />
</form>

posts/templates/posts/index.html
<h1>Home</h1>

<a href="{% url 'posts:create' %}">Create a new post</a>
<br/>

{% for post in posts.all %}

<h1><a href="/posts/show/{{ post.id }}">{{ post.title }}</a></h1>
<a href="{{ post.url }}">View this link</a>
<h3>{{ post.pub_date }}</h3>
<h3>{{ post.author.username }}</h3>

<form method="POST" action="{% url 'posts:upvote' post.id %}">
  {% csrf_token %}
  <input type="submit" value="up" />
</form>

<form method="POST" action="{% url 'posts:downvote' post.id %}">
  {% csrf_token %}
  <input type="submit" value="down" />
</form>

<h3>{{ post.votes_total }} - votes</h3>

<hr/>

{% endfor %}

posts/templates/posts/show.html
<h1>{{ post.title }}</h1>
<a href="{{ post.url }}">View this link</a>
<h3>{{ post.pub_date }}</h3>
<h3>{{ post.author.username }}</h3>
<br/>
<a href="{% url 'home' %}">Go Home</a>